### ISSUE TITLE
Material reference gives NoneType

### ISSUE THREAD

**Issue by EatMeReturns** [lsalzman/iqm#18]
When I was attempting to export, I had issues with "data.materials[matindex] giving NoneType and crashing the Blender v2.64 exporter (I'm running Blender v2.69 on Linux). I made the following quick fix at line #855:
```python
matprefix = ((data.materials and data.materials[matindex]) and data.materials[matindex].name) or ''
```
The change in question is to check if data.materials[matindex] exists before referencing its name attribute.

**Comment by lsalzman** [comment]
Okay, fixed.
