### ISSUE TITLE
[request] a far more modern context

### ISSUE THREAD

**Issue by Tcll** [lsalzman/iqm#22]
love the source for the gpu-demo as I can't seem to find a modern-GL source that beats it.

but the problem I have with it is it uses GLUT which is far outdated and completely unsupportive of most modern event controls.

if I may recommend a port to GLFW (not SDL), I think that'd make things quite a bit more modern. :)
(in my experience, SDL has been known to delete the GL context on window resize and even cause loss of mouse control on linux)

porting to GLFW is actually really easy and works just like GLUT, but with better than SDL event functionality. ;)

the only problem with GLFW is you (currently) need to create a new window for a fullscreen event.

**Comment by lsalzman** [comment]
Thanks for the tip, but I am happier staying with SDL.
