### ISSUE TITLE
order of vertex data

### ISSUE THREAD

**Issue by heitaoflower** [lsalzman/iqm#30]
Hi I have a small question about the order of vertex data  in iqm.
Why we take up zxy as the default order, are there any specific meaning?

**Comment by shakesoda** [comment]
it's using blender's coordinate system, where z=up, x=right, y=forward.

**Comment by exezin** [comment]
It's not a **bug**, just rotate your model before export, modify the iqm exporter, or just swap the Y and Z on import.  There's no defined standard as to what the up-axis should be anyway.

**Comment by heitaoflower** [comment]
Ok, Got it, I just changed the order of vertex as xyz , instead of zxy.
