### ISSUE TITLE
Blender 2.80 iqm_exporter.py, bpy library changes

### ISSUE THREAD

**Issue by raysan5** [lsalzman/iqm#31]
When trying to activate `iqm_exporter.py` addon with latest Blender 2.80, it gives an error on `register()`/`unregister()` functions. 

That's related to `bpy.utils.register_module` [being removed](https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Addons#Registration). I tried implementing the proposed solution:
```py
__classes__ = (
    ExportIQM,
)

def register():
    #bpy.utils.register_module(__name__)
    for c in __classes__:
        bpy.utils.register_class(c)
    bpy.types.TOPBAR_MT_file_export.append(menu_func)

def unregister():
    #bpy.utils.unregister_module(__name__)
    for c in reversed(__classes__):
        bpy.utils.unregister_class(c)
    bpy.types.TOPBAR_MT_file_export.remove(menu_func)
```
Not sure if that's enough or other classes should also be registered.

**Comment by lsalzman** [comment]
Fixed.

**Comment by raysan5** [comment]
Wow! That was fast! Thanks! :)
