### ISSUE TITLE
Blender 2.81a exported model deformed

### ISSUE THREAD

**Issue by hemebond** [lsalzman/iqm#44]
When exporting from Blender 2.81a, and the latest exporter, to use in Quake, the animations are exported but the model is deformed.

![Deformed Demon](https://cdn.discordapp.com/attachments/501516021207662615/715904730802552842/unknown.png)

It looks and works fine in the editor, but I don't actually know if there are issues with the blend file.

[demon.zip](https://github.com/lsalzman/iqm/files/4733247/demon.zip)

Exported using this animation string: `stand:0:13,walk:0:7,run:0:5,jump:0:10,pain:0:5,die:0:9,attack:0:13`

**Comment by hemebond** [comment]
Tagging @q009

**Comment by hemebond** [comment]
Okay! If I de-select "Modifiers" when exporting it all comes out fine.

**Comment by q009** [comment]
@hemebond the mesh you export must have armature modifier disabled if you want to have modifiers. Then, to export you have to select both the mesh and then the armature. I checked it on my end and it exports fine that way.

**Comment by hemebond** [comment]
@q009 Not sure what that means but I'll look into it. Thank you very much for checking this out.

**Comment by shakesoda** [comment]
fwiw, this is very much an exporter bug. you have to do something to this effect to apply modifiers without the armature interfering https://github.com/excessive/iqm-exm/blob/master/blender-2.80/exm_export.py#L1127-L1141

**Comment by q009** [comment]
@shakesoda cheers for the tip, just made a PR for this
