### ISSUE TITLE
imq can't read files???

### ISSUE THREAD

**Issue by chriscamacho** [lsalzman/iqm#46]
okay i know I'm probably holding this wrong (I hope) and I sorry it that is the case !

    [chris@chris-N150CU iqm]$ ./iqm robot.iqm robot.fbx
    failed reading: robot.fbx

not sure if its talking about file access or if its loaded the file and doesn't like something inside it???

[robot.zip](https://github.com/lsalzman/iqm/files/5358677/robot.zip)

**Comment by Calinou** [comment]
The README states:

> FBX (7.x/ascii only)

`robot.fbx` probably uses a more recent version or is a binary file.

**Comment by chriscamacho** [comment]
doh - sorry...
