### ISSUE TITLE
Keep order of materials on export

### ISSUE THREAD

**Issue by OrdinaryMagician** [lsalzman/iqm#59]
I have noticed when exporting a mesh with multiple materials that the material assignments sometimes get shuffled around on the IQM file. This is far from intuitive and becomes a problem when I want to dynamically replace textures in the engine I use, and the indices don't match the source file.

Would it be possible to fix this?

**Comment by lsalzman** [comment]
I can attempt it. Give me a bit to see if I can come up with something.

**Comment by lsalzman** [comment]
I tried a quick hack on the 2.93 exporter. Can you test it for me to see if I any good?

**Comment by OrdinaryMagician** [comment]
It's working correctly now, yes.
