### ISSUE TITLE
Duplicate Mesh Export

### ISSUE THREAD

**Issue by jacob-herrera** [lsalzman/iqm#62]
In commit b8152c6 from issue #60 for the blender-2.93 exporter, it seems like @PJB3005 added an option to export multiple meshes from multiple materials for his DarkPlaces project. I don't even have this option enabled in the blender export and it's exporting the same mesh twice, I assume because the occurrence of `meshes.append(mesh)` twice. For me it was showing as two surfaces in FTEQW. When reading the .iqe file and the blender console, it wrote the same mesh and same material twice.

I just test commit 73112b6 and it has the expected behavior

**Comment by lsalzman** [comment]
Fixed

**Comment by PJB3005** [comment]
I ran into this two weeks ago because I started screwing around with DarkPlaces again and genuinely have no idea how I managed to break that and not notice it, sorry.
